name: website

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
        
      - name: Pull bibeasy
        uses: actions/checkout@main
        with:
          repository: neuropoly/bibeasy
          path: ./bibeasy/
      
      - name: Build bibeasy
        run: |
          cd ./bibeasy/ && pip install .
          cd ../publications/
          python ../bibeasy/bibeasy/scripts/bibeasy_cli.py -l ../bibeasy/bibeasy/labels_publication.txt --type article conf-article --reverse --freshen-cache --combine -o gen.md
          
      - name: remove unused files
        run: |
          rm publications/gen-article.md publications/gen-conf-article.md
          
      - name: Install dependencies
        run: |
          pip install '.[sphinx]'

      - name: Build website
        run: |
          make html

      # TODO: use @v4 when it comes out
      #       to benefit from symlink-awareness: https://github.com/peaceiris/actions-gh-pages/issues/643
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          cname: neuro.polymtl.ca
